#!/usr/bin/env bash
sudo ls >>/dev/null
cid=$(sudo docker container ls | grep sonarqube | awk '{print $1}')
if [ ! -z "$cid" ]; then
	echo "Stopping SonarQube container $cid"
	sudo docker stop $cid
fi
