#!/usr/bin/env bash
function backupFileAsRoot {
    if [ ! -f "$1" ]; then
        return
    fi
    if [ ! -f "$1.ORIGINAL" ]; then
        sudo cp $1 $1.ORIGINAL
    fi
}

tmpy=/etc/scalpel/scalpel.conf
backupFileAsRoot $tmpy
sudo cp $(pwd)/scalpel.conf /etc/scalpel/
unzip ./images.zip
wget https://www.honeynet.org/challenge2010/downloads/hn_forensics.tgz 
tar -xvf ./hn_forensics.tgz
mv Bob.vmem ./images/
rm -f ./hn_forensics.tgz 
